### ISSUE TITLE
The app won't launch - webkit 6 issue?

### ISSUE THREAD

**Issue by mapleroyal** [axel358/Waydroid-Settings#13]
EDIT: my system is a freshly installed vanilla arch linux in gnome, no vm involved.

I installed by aur and by the script here.

When running from aur, it simply never loads. If I call `waydroidsettings` by CLI, I get the following:

```
Traceback (most recent call last):
  File "/usr/bin/waydroidsettings", line 43, in <module>
    from waydroidsettings import main
  File "/usr/share/waydroidsettings/waydroidsettings/main.py", line 24, in <module>
    from .window import WaydroidsettingsWindow
  File "/usr/share/waydroidsettings/waydroidsettings/window.py", line 26, in <module>
    gi.require_version('WebKit', '6.0')
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available
```

When running the app as installed from the script, it also never loads.

**Comment by axel358** [comment]
the gtk4 port is far from being complete, what error do u get when installing from the script provided in this repo?

**Comment by mapleroyal** [comment]
> the gtk4 port is far from being complete, what error do u get when installing from the script provided in this repo?

I don't know how to launch that one from the CLI, so I couldn't get any output. I ended up reimaging my machine to th latest backup because it bothers me when things break or are broken and I don't have time to investigate and repair.

**Comment by axel358** [comment]
waydroid-settings.sh

**Comment by mapleroyal** [comment]
> waydroid-settings.sh

On a brand new linux install from scratch, I get the following:

```
>>> waydroid-settings.sh

Traceback (most recent call last):
  File "/usr/share/waydroid-settings/./waydroid-settings.py", line 10, in <module>
    gi.require_version('WebKit2', '4.0')
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace WebKit2 not available for version 4.0
```

It never opens.

**Comment by mapleroyal** [comment]
ChatGPT came through. This command works:

`sudo pacman -S webkit2gtk`

And then the settings app launches with

`waydroid-settings.sh`

**Comment by axel358** [comment]
do you have https://archlinux.org/packages/extra/x86_64/webkit2gtk/ installed?

**Comment by axel358** [comment]
https://github.com/axel358/waydroid-settings#requirements

**Comment by mapleroyal** [comment]
Ya no I get it, but the pacman packages usually handle dependencies, so this was unexpected for the OP. Regarding your script, it's at https://github.com/axel358/waydroid-settings#install. Guess I wasn't expecting a one-command autoinstall that doesn't install the requirements...? :/

**Comment by axel358** [comment]
the script can't figure out the name of the packages and the package manager used by every distro out there

**Comment by mapleroyal** [comment]
No I get it. I'm relatively new to Linux, but my feedback would be to include requirements as a subheading of the installation instructions. Just my opinion, I've seen it in other guides.

**Comment by axel358** [comment]
Best we can do is provide the list of packages required for the most used distros

**Comment by mapleroyal** [comment]
Right no I get that. And I appreciate your work by the way. My suggestion was not to find a list and put it in your requirements section. But rather consider moving the existing requirements section to be a subheading of installation instructions.

---

Step 1. Requirements:
    Make sure you've installed these packages for your system. <packages>
Step 2. Run the installer:
    Run this script <script>.

**Comment by axel358** [comment]
Suggestions are always welcome, for now i just added the commands to install the deps to the readme, but in the future we can look into adding better ways of automation

**Comment by mapleroyal** [comment]
> Suggestions are always welcome, for now i just added the commands to install the deps to the readme, but in the future we can look into adding better ways of automation

Appreciate your receptiveness. Again, thanks for what you do for us for free.

**Comment by nacull** [comment]
Tried to install it on Zorin 18.1 Gnome with webkit2 v4.1. The following command solved this issue for me:
`sudo sed -i "s/gi.require_version('WebKit2', '4.0')/gi.require_version('WebKit2', '4.1')/g" /usr/lib/waydroid-settings/waydroid-settings.py`

**Comment by DUCKYPAPAKI** [comment]
> Tried to install it on Zorin 18.1 Gnome with webkit2 v4.1. The following command solved this issue for me: `sudo sed -i "s/gi.require_version('WebKit2', '4.0')/gi.require_version('WebKit2', '4.1')/g" /usr/lib/waydroid-settings/waydroid-settings.py`

This was required for me too in order to make it run on Arch linux as of today
